appName: currencyservice
appReplicas: 2
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
appVersion: v0.10.2
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: DISABLE_PROFILER
  value: "1"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
  

servicePort: 7000
