appName: emailservice
appReplicas: 2
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
appVersion: v0.10.2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

servicePort: 5000

# helm template -f values/email-service-values.yaml charts/microservice
# helm lint -f values/email-service-values.yaml charts/microservice  --> Check the correctness and validity of helm yaml files.
# helm install -f values/email-service-values.yaml emailservice charts/microservice
# helm ls