appName: paymentservice
appReplicas: 2
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
appVersion: v0.10.2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "1"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
  

servicePort: 50051
