appName: recommendationservice
appReplicas: 2
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
appVersion: v0.10.2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_PROFILER
  value: "1"

resources:
  requests:
    cpu: 100m
    memory: 220Mi
  limits:
    cpu: 200m
    memory: 450Mi
  

servicePort: 8080

