appName: servicename
appReplicas: 1
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/servicename
appVersion: v0.0.0
containerPort: 8080
containerEnvVars:
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
  

servicePort: 8080
serviceType: ClusterIP
