apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.containerPort }}
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.containerPort }}
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        volumeMounts:
          - name: {{ .Values.volumeName }}
            mountPath: {{ .Values.containerMountPath }}
      volumes:
        - name: {{ .Values.volumeName }}
          emptyDir: {}
