apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique
resources:
  - ../../base

images:
  - name: gcr-adservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    newTag: v0.10.2
  - name: gcr-cartservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    newTag: v0.10.2
  - name: gcr-checkoutservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    newTag: v0.10.2
  - name: gcr-currencyservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    newTag: v0.10.2
  - name: gcr-emailservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    newTag: v0.10.2
  - name: gcr-frontend
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newTag: v0.10.2
  - name: gcr-paymentservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newTag: v0.10.2
  - name: gcr-productcatalogservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    newTag: v0.10.2
  - name: gcr-recommendationservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    newTag: v0.10.2
  - name: gcr-shippingservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    newTag: v0.10.2




# kubectl apply -k overlays/dev


